'use client';

import React, { useState } from 'react';
import {
  Sparkles,
  X,
  Route,
  Globe,
  Mountain,
  Skull,
  CheckCircle2,
  AlertCircle,
  Wand2,
} from 'lucide-react';
import { WorldBible, WorldTradeRoute, MapTerrainFeature } from '@/lib/types';
import { notify } from '@/lib/notify';

interface CartographerAiOracleModalProps {
  worldBible: WorldBible;
  isOpen: boolean;
  onClose: () => void;
  onApplyGeneratedRoutes: (routes: WorldTradeRoute[]) => void;
  onApplyGeneratedTerrain: (features: MapTerrainFeature[]) => void;
  isPersian: boolean;
}

export const CartographerAiOracleModal: React.FC<CartographerAiOracleModalProps> = ({
  worldBible,
  isOpen,
  onClose,
  onApplyGeneratedRoutes,
  onApplyGeneratedTerrain,
  isPersian,
}) => {
  const [selectedPromptMode, setSelectedPromptMode] = useState<
    'trade_network' | 'geographic_seed' | 'wilderness_hazards'
  >('trade_network');
  const [customPrompt, setCustomPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  if (!isOpen) return null;

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      const locations = worldBible.locations || [];
      if (selectedPromptMode === 'trade_network') {
        if (locations.length < 2) {
          notify.error(
            isPersian
              ? 'برای ساخت شاهراه تجاری حداقل ۲ شهر یا مکان روی نقشه نیاز است'
              : 'At least 2 settlements are required to generate trade routes'
          );
          setIsGenerating(false);
          return;
        }

        // Simulate intelligent generation connecting settlement pairs
        const newRoutes: WorldTradeRoute[] = [];
        for (let i = 0; i < locations.length - 1; i++) {
          const orig = locations[i];
          const dest = locations[i + 1];

          // Compute intermediate waypoints between orig & dest
          const p1 = orig.coordinates || { x: 500, y: 500 };
          const p2 = dest.coordinates || { x: 900, y: 700 };
          const midX = Math.round((p1.x + p2.x) / 2 + (Math.random() * 80 - 40));
          const midY = Math.round((p1.y + p2.y) / 2 + (Math.random() * 80 - 40));

          const routeId = `tr_${Date.now().toString(36)}_${i}`;
          newRoutes.push({
            id: routeId,
            name: isPersian
              ? `شاهراه ${orig.name} به ${dest.name}`
              : `Trade Corrdior: ${orig.name} - ${dest.name}`,
            originLocationId: orig.id,
            destinationLocationId: dest.id,
            status: i % 2 === 0 ? 'active' : 'raided',
            dangerLevel: (Math.min(5, Math.max(1, (orig.dangerLevel + dest.dangerLevel) / 2))) as any,
            smugglingRiskDC: 12 + i * 2,
            description: isPersian
              ? `مسیر تردد کاروان‌های شتر و قاطر میان ${orig.name} و ${dest.name}، حامل ادویه و فلزات گرانبها`
              : `Caravan thoroughfare transporting spices, textiles, and ore between ${orig.name} and ${dest.name}`,
            waypoints: [{ x: midX, y: midY }],
            commodities: [
              { entityId: 'comm_silk', name: isPersian ? 'ابریشم زرین' : 'Golden Silk', flowDirection: 'forward' },
              { entityId: 'comm_salt', name: isPersian ? 'نمک بلورین' : 'Rock Salt', flowDirection: 'backward' },
            ],
          });
        }

        onApplyGeneratedRoutes(newRoutes);
        notify.success(
          isPersian
            ? `${newRoutes.length} شاهراه تجاری جدید با موفقیت توسط هوش مصنوعی ترسیم شد`
            : `${newRoutes.length} trade routes successfully generated by AI`
        );
        onClose();
      } else if (selectedPromptMode === 'geographic_seed') {
        // Propose new natural terrain features
        const newTerrain: MapTerrainFeature[] = [
          {
            id: `terr_gen_peaks_${Date.now().toString(36)}`,
            name: isPersian ? 'ستیغ کوهستان صاعقه' : 'Thunder Ridge Crest',
            type: 'mountain_range',
            points: [
              { x: 400, y: 800 },
              { x: 750, y: 850 },
              { x: 1100, y: 920 },
            ],
            elevation: 3200,
            width: 35,
            climateZone: 'polar',
            description: isPersian ? 'دیواره صخره‌ای آذرخش‌گیر در جنوب دشت' : 'Jagged lightning-attracting peaks',
          },
          {
            id: `terr_gen_river_${Date.now().toString(36)}`,
            name: isPersian ? 'شط مروارید سیاه' : 'Black Pearl Torrent',
            type: 'river',
            points: [
              { x: 1100, y: 930 },
              { x: 1300, y: 1100 },
              { x: 1450, y: 1350 },
            ],
            width: 4,
            color: '#38bdf8',
            description: isPersian ? 'رودخانه خروشان سرازیر از کوهسار به خلیج جنوبی' : 'Torrent flowing to southern gulf',
          },
        ];

        onApplyGeneratedTerrain(newTerrain);
        notify.success(
          isPersian
            ? 'عوارض طبیعی و کوهستان‌های جدید به نقشه اضافه شدند'
            : 'New natural terrain features added to the map'
        );
        onClose();
      }
    } catch (err: any) {
      notify.error(err?.message || 'AI Generation error');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm select-none animate-fadeIn">
      <div className="w-full max-w-lg bg-zinc-950 border border-zinc-800 rounded-3xl p-6 shadow-2xl flex flex-col gap-5">
        {/* Header */}
        <div className="flex items-center justify-between pb-3 border-b border-zinc-800/80">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-violet-500/10 border border-violet-500/30 flex items-center justify-center text-violet-400">
              <Sparkles className="w-4.5 h-4.5" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-zinc-100">
                {isPersian ? 'نقشه‌نگار هوشمند (AI World Co-Pilot)' : 'AI Cartographer Oracle'}
              </h2>
              <p className="text-xs text-zinc-400">
                {isPersian ? 'ترسیم خودکار اقلیم، مسیر کاروان‌ها و عوارض سیاره' : 'Procedural geography & trade generation'}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-zinc-400 hover:text-zinc-100 rounded-xl hover:bg-zinc-900 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Mode Selector */}
        <div className="grid grid-cols-2 gap-2 text-xs">
          <button
            onClick={() => setSelectedPromptMode('trade_network')}
            className={`p-3 rounded-2xl border text-left flex flex-col gap-1 transition-all ${
              selectedPromptMode === 'trade_network'
                ? 'bg-amber-500/10 border-amber-500/40 text-amber-300'
                : 'bg-zinc-900 border-zinc-800 text-zinc-400 hover:border-zinc-700'
            }`}
          >
            <Route className="w-4 h-4 text-amber-400" />
            <div className="font-semibold text-zinc-200 mt-1">
              {isPersian ? 'شبکه شاهراه‌های تجاری' : 'Caravan Network'}
            </div>
            <div className="text-[11px] text-zinc-500 leading-tight">
              {isPersian ? 'اتصال هوشمند شهرهای نقشه با کاروان‌ها و کالاهای تجاری' : 'Auto-link settlements with trade corridors'}
            </div>
          </button>

          <button
            onClick={() => setSelectedPromptMode('geographic_seed')}
            className={`p-3 rounded-2xl border text-left flex flex-col gap-1 transition-all ${
              selectedPromptMode === 'geographic_seed'
                ? 'bg-emerald-500/10 border-emerald-500/40 text-emerald-300'
                : 'bg-zinc-900 border-zinc-800 text-zinc-400 hover:border-zinc-700'
            }`}
          >
            <Mountain className="w-4 h-4 text-emerald-400" />
            <div className="font-semibold text-zinc-200 mt-1">
              {isPersian ? 'عوارض طبیعی و کوهستان' : 'Natural Terrain'}
            </div>
            <div className="text-[11px] text-zinc-500 leading-tight">
              {isPersian ? 'تولید رشته‌کوه‌ها، دره‌ها و رودخانه‌ها بر اساس درون‌مایه جهان' : 'Spine mountains, rivers & chasms'}
            </div>
          </button>
        </div>

        {/* World Premise Context */}
        <div className="p-3 bg-zinc-900/60 border border-zinc-800/80 rounded-2xl text-xs space-y-1">
          <div className="text-zinc-500 text-[10px] uppercase font-mono">{isPersian ? 'بستر روایت جهان' : 'World Lore Premise'}</div>
          <div className="text-zinc-300 line-clamp-2">
            {worldBible.summary || (isPersian ? 'دنیایی اساطیری با کویرهای سرخ و شهرهای باستانی' : 'A mythic world of red deserts and ancient citadels')}
          </div>
        </div>

        {/* Custom Directives Input */}
        <div>
          <label className="text-xs text-zinc-400 block mb-1 font-medium">
            {isPersian ? 'دستورات ویژه یا راهنمایی دلخواه (اختیاری):' : 'Custom Guidance (Optional):'}
          </label>
          <input
            type="text"
            value={customPrompt}
            onChange={(e) => setCustomPrompt(e.target.value)}
            placeholder={isPersian ? 'مثال: مسیرهای خطرناک کوهستانی با راهزنان ادویه...' : 'e.g., Hazardous mountain passes plagued by raiders...'}
            className="w-full bg-zinc-900 border border-zinc-800 text-zinc-200 text-xs rounded-xl px-3 py-2 focus:outline-none focus:border-amber-500/50"
          />
        </div>

        {/* Footer Actions */}
        <div className="flex items-center justify-end gap-2.5 pt-2 border-t border-zinc-800/80">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl text-xs font-medium text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900 transition-colors"
          >
            {isPersian ? 'انصراف' : 'Cancel'}
          </button>
          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="flex items-center gap-2 px-5 py-2 rounded-xl text-xs font-semibold bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500 text-white shadow-lg shadow-violet-950/50 transition-all disabled:opacity-50"
          >
            {isGenerating ? (
              <div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" />
            ) : (
              <Wand2 className="w-3.5 h-3.5" />
            )}
            <span>{isGenerating ? (isPersian ? 'در حال پردازش...' : 'Synthesizing...') : (isPersian ? 'تولید و اعمال روی نقشه' : 'Generate & Apply')}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
