'use client';

import React, { useState } from 'react';
import { useStudioStory } from '@/lib/context/StudioStoryContext';
import {
  Clock,
  Plus,
  Trash2,
  Edit2,
  Calendar,
  Layers,
  Sparkles,
  Shield,
  MapPin,
  Lock,
  Eye,
  EyeOff,
  Flame,
  Crown,
  History,
  X,
  Check,
} from 'lucide-react';
import { TimelineEvent } from '@/lib/types';
import { notify } from '@/lib/notify';

export default function TimelineStudioPage() {
  const { story, isPersian, addTimelineEvent, editTimelineEvent, deleteTimelineEvent } = useStudioStory();

  const [filterEra, setFilterEra] = useState<string>('all');
  const [showAddModal, setShowAddModal] = useState<boolean>(false);
  const [editingEventId, setEditingEventId] = useState<string | null>(null);

  // Form State
  const [eventTitle, setEventTitle] = useState('');
  const [eventYear, setEventYear] = useState('');
  const [eventCategory, setEventCategory] = useState<'ancient' | 'war' | 'reign' | 'cataclysm' | 'present'>('ancient');
  const [eventSummary, setEventSummary] = useState('');
  const [eventSignificance, setEventSignificance] = useState('');
  const [eventIsPublic, setEventIsPublic] = useState(true);
  const [eventSecretDetails, setEventSecretDetails] = useState('');
  const [eventLinkedFactions, setEventLinkedFactions] = useState<string[]>([]);
  const [eventLinkedLocations, setEventLinkedLocations] = useState<string[]>([]);

  const timeline = story.worldBible.timeline || [];
  const factions = story.worldBible.factions || [];
  const locations = story.worldBible.locations || [];

  const filteredTimeline = timeline.filter((evt) => {
    if (filterEra === 'all') return true;
    if (filterEra === 'secret') return !evt.knownByPublic;
    if (filterEra === 'public') return evt.knownByPublic;
    return evt.eraCategory === filterEra;
  });

  const handleOpenAddModal = () => {
    setEditingEventId(null);
    setEventTitle('');
    setEventYear('');
    setEventCategory('ancient');
    setEventSummary('');
    setEventSignificance('');
    setEventIsPublic(true);
    setEventSecretDetails('');
    setEventLinkedFactions([]);
    setEventLinkedLocations([]);
    setShowAddModal(true);
  };

  const handleOpenEditModal = (evt: TimelineEvent) => {
    setEditingEventId(evt.id);
    setEventTitle(evt.title);
    setEventYear(evt.yearOrEra);
    setEventCategory((evt.eraCategory as any) || 'ancient');
    setEventSummary(evt.summary);
    setEventSignificance(evt.significance || '');
    setEventIsPublic(evt.knownByPublic);
    setEventSecretDetails(evt.secretDetails || '');
    setEventLinkedFactions(evt.linkedFactionIds || []);
    setEventLinkedLocations(evt.linkedLocationIds || []);
    setShowAddModal(true);
  };

  const handleSaveEvent = (e: React.FormEvent) => {
    e.preventDefault();
    if (!eventTitle.trim() || !eventYear.trim()) {
      notify.error(isPersian ? 'عنوان رویداد و زمان آن الزامی است' : 'Event title and year/era are required');
      return;
    }

    const payload: TimelineEvent = {
      id: editingEventId || `evt_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 6)}`,
      yearOrEra: eventYear.trim(),
      title: eventTitle.trim(),
      summary: eventSummary.trim(),
      significance: eventSignificance.trim(),
      knownByPublic: eventIsPublic,
      eraCategory: eventCategory,
      secretDetails: eventSecretDetails.trim() || undefined,
      linkedFactionIds: eventLinkedFactions,
      linkedLocationIds: eventLinkedLocations,
    };

    if (editingEventId) {
      editTimelineEvent(editingEventId, payload);
    } else {
      addTimelineEvent(payload);
    }

    setShowAddModal(false);
  };

  const [isGeneratingAi, setIsGeneratingAi] = useState(false);

  const handleAiGenerate = async () => {
    setIsGeneratingAi(true);
    try {
      const res = await fetch('/api/studio/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          type: 'timeline_event',
          isPersian,
          themeContext: story.worldBible.themeNotes,
        }),
      });
      const json = await res.json();
      if (json.success && json.data) {
        addTimelineEvent({
          id: `evt_${Date.now().toString(36)}`,
          yearOrEra: json.data.yearOrEra || '۱۰۰ سال پیش',
          title: json.data.title || 'رویداد تاریخی مهم',
          summary: json.data.summary || '',
          significance: json.data.significance || '',
          knownByPublic: json.data.knownByPublic ?? true,
          eraCategory: json.data.eraCategory || 'war',
        });
        notify.success(isPersian ? 'رویداد تاریخی توسط هوش مصنوعی با موفقیت خلق شد' : 'Historical event generated by AI');
      } else {
        notify.error(isPersian ? 'خطا در تولید رویداد' : 'Failed to generate event');
      }
    } catch {
      notify.error(isPersian ? 'خطا در ارتباط با هوش مصنوعی' : 'AI connection error');
    } finally {
      setIsGeneratingAi(false);
    }
  };

  const getEraBadge = (era?: string) => {
    switch (era) {
      case 'ancient':
        return { label: isPersian ? 'عصر باستان' : 'Ancient Era', color: 'text-amber-400 bg-amber-500/10 border-amber-500/30' };
      case 'war':
        return { label: isPersian ? 'جنگ و کشمکش' : 'War / Conflict', color: 'text-rose-400 bg-rose-500/10 border-rose-500/30' };
      case 'reign':
        return { label: isPersian ? 'دوران سلطنت' : 'Reign / Golden Era', color: 'text-indigo-400 bg-indigo-500/10 border-indigo-500/30' };
      case 'cataclysm':
        return { label: isPersian ? 'فاجعه کیهانی' : 'Cataclysm', color: 'text-red-400 bg-red-500/10 border-red-500/30' };
      case 'present':
        return { label: isPersian ? 'عصر معاصر' : 'Present Era', color: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30' };
      default:
        return { label: isPersian ? 'رویداد تاریخی' : 'Historical Milestone', color: 'text-sky-400 bg-sky-500/10 border-sky-500/30' };
    }
  };

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Header Banner */}
      <div className="bg-zinc-900/60 border border-zinc-800/80 rounded-3xl p-6 md:p-8 backdrop-blur-sm shadow-xl flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2.5 mb-1.5">
            <Clock className="w-5 h-5 text-amber-400" />
            <h2 className="text-xl md:text-2xl font-bold text-zinc-100">
              {isPersian ? 'گاه‌شمار تاریخی و اعصار جهان' : 'Historical Chronicle & Eras'}
            </h2>
          </div>
          <p className="text-sm text-zinc-400 max-w-3xl leading-relaxed">
            {isPersian
              ? 'ثبت و مدیریت وقایع‌نگاری تاریخی، اعصار کهن، نبردهای سرنوشت‌ساز و اسرار تاریخی که به هوش مصنوعی عمق روایی می‌دهند.'
              : 'Chronicle historical epochs, ancient wars, and forbidden lore that fuel historical context and Arcana checks.'}
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={handleAiGenerate}
            disabled={isGeneratingAi}
            className="px-3.5 py-2 rounded-2xl bg-zinc-800 hover:bg-zinc-700 border border-zinc-700 text-amber-300 text-xs font-bold flex items-center gap-1.5 transition-all shadow-md disabled:opacity-50"
          >
            <Sparkles className={`w-3.5 h-3.5 ${isGeneratingAi ? 'animate-spin' : 'text-amber-400'}`} />
            <span>{isGeneratingAi ? (isPersian ? 'در حال خلق...' : 'Generating...') : (isPersian ? '⚡ دستیار هوش مصنوعی' : '⚡ AI Co-Pilot')}</span>
          </button>
          <span className="text-xs bg-amber-500/10 border border-amber-500/20 text-amber-300 px-3.5 py-2 rounded-xl font-mono flex items-center gap-1.5">
            <History className="w-3.5 h-3.5 text-amber-400" />
            {timeline.length} {isPersian ? 'رویداد ثبت‌شده' : 'Chronicle Events'}
          </span>
          <button
            onClick={handleOpenAddModal}
            className="px-4 py-2 rounded-2xl bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 text-zinc-950 text-xs font-bold shadow-lg shadow-amber-500/20 flex items-center gap-1.5 transition-all"
          >
            <Plus className="w-4 h-4" />
            <span>{isPersian ? '+ ثبت رویداد جدید' : '+ Add Chronicle Event'}</span>
          </button>
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center gap-2 border-b border-zinc-800 pb-3 overflow-x-auto">
        <button
          onClick={() => setFilterEra('all')}
          className={`px-4 py-2 rounded-2xl text-xs font-bold transition-all ${
            filterEra === 'all'
              ? 'bg-amber-500/10 border border-amber-500/30 text-amber-400 shadow-md'
              : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900/60 border border-transparent'
          }`}
        >
          {isPersian ? 'همه وقایع' : 'All Events'} ({timeline.length})
        </button>
        <button
          onClick={() => setFilterEra('ancient')}
          className={`px-4 py-2 rounded-2xl text-xs font-bold transition-all ${
            filterEra === 'ancient'
              ? 'bg-amber-500/10 border border-amber-500/30 text-amber-400 shadow-md'
              : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900/60 border border-transparent'
          }`}
        >
          {isPersian ? 'عصر باستان' : 'Ancient Eras'}
        </button>
        <button
          onClick={() => setFilterEra('war')}
          className={`px-4 py-2 rounded-2xl text-xs font-bold transition-all ${
            filterEra === 'war'
              ? 'bg-amber-500/10 border border-amber-500/30 text-amber-400 shadow-md'
              : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900/60 border border-transparent'
          }`}
        >
          {isPersian ? 'جنگ‌ها و بحران‌ها' : 'Wars & Crises'}
        </button>
        <button
          onClick={() => setFilterEra('reign')}
          className={`px-4 py-2 rounded-2xl text-xs font-bold transition-all ${
            filterEra === 'reign'
              ? 'bg-amber-500/10 border border-amber-500/30 text-amber-400 shadow-md'
              : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900/60 border border-transparent'
          }`}
        >
          {isPersian ? 'دوران سلطنت' : 'Reigns'}
        </button>
        <button
          onClick={() => setFilterEra('present')}
          className={`px-4 py-2 rounded-2xl text-xs font-bold transition-all ${
            filterEra === 'present'
              ? 'bg-amber-500/10 border border-amber-500/30 text-amber-400 shadow-md'
              : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900/60 border border-transparent'
          }`}
        >
          {isPersian ? 'عصر معاصر' : 'Present Era'}
        </button>
        <button
          onClick={() => setFilterEra('secret')}
          className={`px-4 py-2 rounded-2xl text-xs font-bold transition-all ${
            filterEra === 'secret'
              ? 'bg-amber-500/10 border border-amber-500/30 text-amber-400 shadow-md'
              : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900/60 border border-transparent'
          }`}
        >
          <span className="flex items-center gap-1.5">
            <Lock className="w-3 h-3 text-red-400" />
            {isPersian ? 'اسرار ممنوعه' : 'Forbidden / Secret Lore'}
          </span>
        </button>
      </div>

      {/* Timeline Stream */}
      <div className="relative pl-6 md:pl-10 space-y-8 before:absolute before:left-3 md:before:left-5 before:top-4 before:bottom-4 before:w-0.5 before:bg-gradient-to-b before:from-amber-500 before:via-purple-500 before:to-emerald-500">
        {filteredTimeline.length === 0 ? (
          <div className="text-center py-16 bg-zinc-900/40 border border-zinc-800/60 rounded-3xl p-8">
            <Clock className="w-12 h-12 text-zinc-600 mx-auto mb-3" />
            <h4 className="text-sm font-bold text-zinc-300">
              {isPersian ? 'رویدادی در این دسته‌بندی یافت نشد' : 'No chronicle events found'}
            </h4>
            <p className="text-xs text-zinc-500 mt-1">
              {isPersian ? 'برای ثبت وقایع تاریخی روی دکمه ثبت رویداد جدید کلیک کنید.' : 'Click "+ Add Chronicle Event" to record history.'}
            </p>
          </div>
        ) : (
          filteredTimeline.map((evt, idx) => {
            const era = getEraBadge(evt.eraCategory);
            const linkedFacObjs = factions.filter((f) => evt.linkedFactionIds?.includes(f.id));
            const linkedLocObjs = locations.filter((l) => evt.linkedLocationIds?.includes(l.id));

            return (
              <div key={evt.id} className="relative group animate-fadeIn">
                {/* Node Dot on Timeline Track */}
                <div className="absolute -left-6 md:-left-10 top-5 w-4 h-4 rounded-full bg-zinc-950 border-2 border-amber-400 shadow-lg shadow-amber-400/30 group-hover:scale-125 transition-transform" />

                {/* Event Card */}
                <div className="bg-zinc-900/60 border border-zinc-800/80 rounded-3xl p-6 backdrop-blur-sm shadow-xl hover:border-zinc-700 transition-all space-y-4">
                  <div className="flex flex-col md:flex-row md:items-center justify-between gap-2 border-b border-zinc-800/60 pb-3">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="text-xs font-mono font-bold text-amber-400 bg-amber-500/10 border border-amber-500/20 px-3 py-1 rounded-xl">
                        {evt.yearOrEra}
                      </span>
                      <span className={`text-[11px] font-bold border px-2.5 py-0.5 rounded-xl ${era.color}`}>
                        {era.label}
                      </span>
                      {evt.knownByPublic ? (
                        <span className="text-[10.5px] text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-2 py-0.5 rounded-lg flex items-center gap-1">
                          <Eye className="w-3 h-3" /> {isPersian ? 'دانش عمومی' : 'Public Lore'}
                        </span>
                      ) : (
                        <span className="text-[10.5px] text-red-400 bg-red-500/10 border border-red-500/20 px-2 py-0.5 rounded-lg flex items-center gap-1">
                          <Lock className="w-3 h-3" /> {isPersian ? 'راز مکتوم (چک Arcana)' : 'Secret Lore'}
                        </span>
                      )}
                    </div>

                    <div className="flex items-center gap-2 self-end md:self-auto">
                      <button
                        onClick={() => handleOpenEditModal(evt)}
                        className="text-zinc-400 hover:text-amber-300 p-1.5 rounded-lg hover:bg-zinc-800 transition-colors"
                      >
                        <Edit2 className="w-3.5 h-3.5" />
                      </button>
                      <button
                        onClick={async () => {
                          const conf = await notify.confirm({
                            title: isPersian ? 'حذف رویداد تاریخی' : 'Delete Timeline Event',
                            message: isPersian
                              ? `آیا از حذف رویداد "${evt.title}" از گاه‌شمار جهان مطمئن هستید؟`
                              : `Are you sure you want to remove "${evt.title}" from the world chronicle?`,
                            confirmText: isPersian ? 'بله، حذف شود' : 'Delete',
                            cancelText: isPersian ? 'انصراف' : 'Cancel',
                            isDestructive: true,
                          });
                          if (conf) deleteTimelineEvent(evt.id);
                        }}
                        className="text-zinc-400 hover:text-red-400 p-1.5 rounded-lg hover:bg-zinc-800 transition-colors"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>

                  <div>
                    <h3 className="text-base font-bold text-zinc-100 mb-1">{evt.title}</h3>
                    <p className="text-xs text-zinc-300 leading-relaxed">{evt.summary}</p>
                  </div>

                  {evt.significance && (
                    <div className="bg-zinc-950/60 border border-zinc-800/80 rounded-2xl p-3.5 text-xs text-zinc-400">
                      <span className="text-amber-400/90 font-bold block mb-1">
                        {isPersian ? 'پیامد و اثر تاریخی در جهان:' : 'Historical Aftermath & Significance:'}
                      </span>
                      <p>{evt.significance}</p>
                    </div>
                  )}

                  {evt.secretDetails && (
                    <div className="bg-red-950/20 border border-red-500/30 rounded-2xl p-3.5 text-xs text-red-300/90">
                      <span className="text-red-400 font-bold flex items-center gap-1.5 mb-1">
                        <Lock className="w-3.5 h-3.5" />
                        {isPersian ? 'جزییات پنهان (فاش‌شده با آزمون‌های دانش کهن):' : 'Secret Lore Context:'}
                      </span>
                      <p>{evt.secretDetails}</p>
                    </div>
                  )}

                  {/* Linked Factions & Locations */}
                  {(linkedFacObjs.length > 0 || linkedLocObjs.length > 0) && (
                    <div className="flex flex-wrap items-center gap-2 pt-2 border-t border-zinc-800/60">
                      {linkedFacObjs.map((f) => (
                        <span key={f.id} className="text-[11px] bg-purple-500/10 border border-purple-500/20 text-purple-300 px-2.5 py-1 rounded-xl flex items-center gap-1">
                          <Shield className="w-3 h-3" /> {f.name}
                        </span>
                      ))}
                      {linkedLocObjs.map((l) => (
                        <span key={l.id} className="text-[11px] bg-sky-500/10 border border-sky-500/20 text-sky-300 px-2.5 py-1 rounded-xl flex items-center gap-1">
                          <MapPin className="w-3 h-3" /> {l.name}
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            );
          })
        )}
      </div>

      {/* Add / Edit Event Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-fadeIn">
          <div className="bg-zinc-900 border border-zinc-700 rounded-3xl p-6 max-w-2xl w-full shadow-2xl space-y-4 max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between border-b border-zinc-800 pb-3">
              <span className="text-sm font-bold text-amber-400 flex items-center gap-2">
                <Clock className="w-4 h-4" />
                {editingEventId
                  ? isPersian
                    ? 'ویرایش رویداد تاریخی'
                    : 'Edit Historical Event'
                  : isPersian
                  ? 'ثبت رویداد تاریخی جدید'
                  : 'Add New Chronicle Event'}
              </span>
              <button
                type="button"
                onClick={() => setShowAddModal(false)}
                className="text-zinc-500 hover:text-zinc-300"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleSaveEvent} className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="text-xs font-bold text-zinc-300 block mb-1.5">
                    {isPersian ? 'عنوان رویداد تاریخی:' : 'Event Title:'}
                  </label>
                  <input
                    type="text"
                    value={eventTitle}
                    onChange={(e) => setEventTitle(e.target.value)}
                    placeholder={isPersian ? 'مثال: نبرد بزرگ و انقراض اژدهایان' : 'e.g. The Great Dragon Extinction War'}
                    className="w-full bg-zinc-950 border border-zinc-700 rounded-xl px-3 py-2 text-xs text-zinc-100 focus:outline-none focus:border-amber-400"
                  />
                </div>

                <div>
                  <label className="text-xs font-bold text-zinc-300 block mb-1.5">
                    {isPersian ? 'زمان وقوع یا عصر تاریخی:' : 'Year or Epoch:'}
                  </label>
                  <input
                    type="text"
                    value={eventYear}
                    onChange={(e) => setEventYear(e.target.value)}
                    placeholder={isPersian ? 'مثال: ۳۰۰ سال پیش (عصر خاکستر)' : 'e.g. 300 Years Ago (Age of Ash)'}
                    className="w-full bg-zinc-950 border border-zinc-700 rounded-xl px-3 py-2 text-xs text-zinc-100 focus:outline-none focus:border-amber-400"
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="text-xs font-bold text-zinc-300 block mb-1.5">
                    {isPersian ? 'دسته‌بندی عصر:' : 'Era Category:'}
                  </label>
                  <select
                    value={eventCategory}
                    onChange={(e) => setEventCategory(e.target.value as any)}
                    className="w-full bg-zinc-950 border border-zinc-700 rounded-xl px-3 py-2 text-xs text-zinc-100 focus:outline-none focus:border-amber-400"
                  >
                    <option value="ancient">{isPersian ? 'عصر باستان و اساطیر' : 'Ancient / Mythic'}</option>
                    <option value="war">{isPersian ? 'جنگ‌ها و نبردهای خونین' : 'War / Crisis'}</option>
                    <option value="reign">{isPersian ? 'دوران سلطنت و سلسله‌ها' : 'Reign / Golden Era'}</option>
                    <option value="cataclysm">{isPersian ? 'فاجعه‌های طبیعی و جادویی' : 'Cataclysm / Anomaly'}</option>
                    <option value="present">{isPersian ? 'دوره معاصر و جاری' : 'Present Day'}</option>
                  </select>
                </div>

                <div>
                  <label className="text-xs font-bold text-zinc-300 block mb-1.5">
                    {isPersian ? 'سطح آگاهی و دسترسی:' : 'Lore Accessibility:'}
                  </label>
                  <label className="flex items-center gap-2 mt-2 cursor-pointer text-xs text-zinc-300">
                    <input
                      type="checkbox"
                      checked={eventIsPublic}
                      onChange={(e) => setEventIsPublic(e.target.checked)}
                      className="rounded accent-amber-500 w-4 h-4"
                    />
                    <span>{isPersian ? 'دانش عمومی (مردم و قهرمان از آن آگاهند)' : 'Publicly Known Lore'}</span>
                  </label>
                </div>
              </div>

              <div>
                <label className="text-xs font-bold text-zinc-300 block mb-1.5">
                  {isPersian ? 'شرح واقعه:' : 'Event Narrative Summary:'}
                </label>
                <textarea
                  rows={3}
                  value={eventSummary}
                  onChange={(e) => setEventSummary(e.target.value)}
                  placeholder={isPersian ? 'توضیح آنچه در تاریخ رخ داده است...' : 'Describe what happened...'}
                  className="w-full bg-zinc-950 border border-zinc-700 rounded-xl px-3 py-2 text-xs text-zinc-100 focus:outline-none focus:border-amber-400"
                />
              </div>

              <div>
                <label className="text-xs font-bold text-zinc-300 block mb-1.5">
                  {isPersian ? 'پیامد و تأثیر تاریخی بر جهان امروز:' : 'Historical Aftermath & Significance:'}
                </label>
                <input
                  type="text"
                  value={eventSignificance}
                  onChange={(e) => setEventSignificance(e.target.value)}
                  placeholder={isPersian ? 'مثال: انقراض کامل اژدهایان و سقوط خاندان کهن' : 'e.g. Extinction of dragonkind and rise of the human empire'}
                  className="w-full bg-zinc-950 border border-zinc-700 rounded-xl px-3 py-2 text-xs text-zinc-100 focus:outline-none focus:border-amber-400"
                />
              </div>

              <div>
                <label className="text-xs font-bold text-red-400 block mb-1.5">
                  {isPersian ? 'اسرار مکتوم و حقایق پنهان واقعه (اختیاری):' : 'Secret Lore Context (Optional):'}
                </label>
                <input
                  type="text"
                  value={eventSecretDetails}
                  onChange={(e) => setEventSecretDetails(e.target.value)}
                  placeholder={isPersian ? 'حقیقتی که فقط با آزمون‌های دانش کهن (Arcana) فاش می‌شود...' : 'Secret facts uncovered through Arcana/History checks...'}
                  className="w-full bg-zinc-950 border border-red-500/30 rounded-xl px-3 py-2 text-xs text-zinc-100 focus:outline-none focus:border-red-400"
                />
              </div>

              <div className="flex items-center justify-end gap-2 pt-2 border-t border-zinc-800">
                <button
                  type="button"
                  onClick={() => setShowAddModal(false)}
                  className="px-4 py-2 rounded-xl bg-zinc-800 text-zinc-300 text-xs font-bold hover:bg-zinc-700"
                >
                  {isPersian ? 'انصراف' : 'Cancel'}
                </button>
                <button
                  type="submit"
                  className="px-5 py-2 rounded-xl bg-amber-500 hover:bg-amber-400 text-zinc-950 text-xs font-bold shadow-lg shadow-amber-500/20"
                >
                  {editingEventId
                    ? isPersian
                      ? 'ذخیره تغییرات'
                      : 'Update Event'
                    : isPersian
                    ? 'ثبت در گاه‌شمار'
                    : 'Save to Chronicle'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
