import { StoryManifest } from '@/lib/types';

export const ghaleSiahsangStory: StoryManifest = {
  id: 'ghale_siahsang',
  title: 'قلعه سیاه‌سنگ',
  tagline: 'در سایه دژ باستانی، انتخاب‌هایت سرنوشت را رقم می‌زنند.',
  synopsis:
    'در اعماق کهن دژ آتشفشانی سیاه‌سنگ بیدار می‌شوی؛ جایی که صدای چکمه‌های زره‌پوش نگهبانان روی سنگ‌های سرد پژواک می‌کند. سیصد سال از نابودی آخرین اژدهایان می‌گذرد، اما در تالار تاج‌وتخت نیرویی به مراتب تاریک‌تر در حال بیداری است.',
  genres: ['dark_fantasy', 'mystery_noir'],
  language: 'fa',
  coverImageUrl: '/covers/ghale_siahsang.webp',
  author: 'استودیو استوری‌فورج',
  version: '1.1.0',
  rpgSystem: {
    hasCombat: true,
    diceType: 'd20',
    stats: [
      { id: 'might', name: 'قدرت بدنی', description: 'توان فیزیکی، استقامت و مبارزه تن‌به‌تن', baseValue: 12 },
      { id: 'agility', name: 'چابکی', description: 'سرعت واکنش، مخفی‌کاری، تعادل و حرکات آکروباتیک', baseValue: 14 },
      { id: 'cunning', name: 'هوش و ذکاوت', description: 'دقت دیداری، فریب، قفل‌گشایی و خرد خیابانی', baseValue: 10 },
      { id: 'arcana', name: 'دانش کهن', description: 'آشنایی با نمادهای باستانی و آثار ممنوعه', baseValue: 8 },
    ],
    resources: [
      { id: 'hp', name: 'سلامتی (HP)', current: 100, max: 100, min: 0, color: '#ef4444' },
      { id: 'stamina', name: 'انرژی (Stamina)', current: 50, max: 50, min: 0, color: '#3b82f6' },
      { id: 'gold', name: 'سکه‌های طلا', current: 30, max: 9999, min: 0, color: '#eab308' },
    ],
    skills: [
      { id: 'blade_mastery', name: 'مهارت در شمشیرزنی', description: 'ضربات دقیق با تیغه', linkedStatId: 'might', tier: 1, bonusModifier: 2 },
      { id: 'shadow_step', name: 'گام‌های بی‌صدا', description: 'حرکت مخفیانه در تاریکی', linkedStatId: 'agility', tier: 1, bonusModifier: 2 },
    ],
    startingInventory: [
      {
        id: 'iron_dagger',
        name: 'خنجر فولادی چکمه',
        description: 'خنجری تیز با تیغه باریک که در درز چکمه پنهان شده.',
        type: 'weapon',
        rarity: 'uncommon',
        grip: 'one_handed',
        quantity: 1,
        statModifiers: { agility: 1, might: 1 },
      },
      {
        id: 'ashwood_buckler',
        name: 'سپر چوبی کهن',
        description: 'سپری گرد از چوب زبان‌گنجشک با لبه‌های آهنی برای دفاع در فضاهای بسته.',
        type: 'shield',
        rarity: 'common',
        grip: 'off_hand_only',
        quantity: 1,
        statModifiers: { might: 1 },
      },
      {
        id: 'greatsword_valoria',
        name: 'شمشیر دو دست گارد سنگ',
        description: 'تیغه‌ای سنگین و دولبه از فولاد تیره که به کار بردنش نیازمند هر دو دست است.',
        type: 'weapon',
        rarity: 'rare',
        grip: 'two_handed',
        quantity: 1,
        statModifiers: { might: 3 },
      },
      {
        id: 'healing_tincture',
        name: 'معجون گیاهی کوهستان',
        description: 'عصاره تلخ گیاهان کوهستانی که ۳۰ واحد سلامتی (HP) را بلافاصله بازیابی می‌کند.',
        type: 'consumable',
        rarity: 'uncommon',
        quantity: 2,
        healValue: 30,
        isConsumable: true,
      },
      {
        id: 'shadow_amulet',
        name: 'طلسم سایه‌روشن',
        description: 'مدالی با سنگ عقیق سیاه که انرژی‌های کهن را بازتاب می‌دهد.',
        type: 'relic',
        rarity: 'rare',
        quantity: 1,
        statModifiers: { arcana: 2, cunning: 1 },
      },
      {
        id: 'lockpick_set',
        name: 'ابزار قفل‌گشایی برنجی',
        description: 'دو میله باریک برنجی در غلاف چرمی برای باز کردن قفل‌های زنگ‌زده.',
        type: 'quest_item',
        rarity: 'common',
        quantity: 1,
        statModifiers: { cunning: 1 },
      },
    ],
    inventoryCapacity: 12,
    archetypes: [
      {
        id: 'shadowblade',
        name: 'سایه‌تیغ',
        tagline: 'استاد نفوذ بی‌صدا، قفل‌گشایی و ضربات مهلک غافلگیرکننده',
        description: 'در سایه‌های قلعه زاده شده‌ای؛ گام‌هایت بی‌صداست و تیغه‌ات پیش از آنکه دیده شود، دشمن را از پای درمی‌آورد.',
        iconName: 'colorize',
        statBonuses: { agility: 2, cunning: 1 },
        startingEquipment: {
          mainHand: 'iron_dagger',
          relic: 'shadow_amulet',
        },
        bonusItems: [
          {
            id: 'smoke_pellet',
            name: 'گلوله دودی گوگردی',
            description: 'انفجار دود غلیظ که حواس دشمنان را منحرف کرده و فرصت فرار ایجاد می‌کند.',
            type: 'consumable',
            rarity: 'uncommon',
            quantity: 2,
            isConsumable: true,
          },
        ],
      },
      {
        id: 'iron_vanguard',
        name: 'سرباز پولادین',
        tagline: 'مدافع سرسخت با تیغه سنگین و زره پولادین نفوذناپذیر',
        description: 'آزموده در میدان‌های نبرد خونین؛ شمشیر دو دست و اراده پولادینت دیواری تسخیرناپذیر در برابر خطرات دژ است.',
        iconName: 'shield',
        statBonuses: { might: 3 },
        startingEquipment: {
          mainHand: 'greatsword_valoria',
        },
        bonusItems: [
          {
            id: 'healing_tincture',
            name: 'معجون گیاهی کوهستان',
            description: 'عصاره تلخ گیاهان کوهستانی که ۳۰ واحد سلامتی (HP) را بازیابی می‌کند.',
            type: 'consumable',
            rarity: 'uncommon',
            quantity: 1,
            healValue: 30,
            isConsumable: true,
          },
        ],
      },
      {
        id: 'arcane_scholar',
        name: 'پژوهشگر کهن',
        tagline: 'کاشف طلسم‌های ممنوعه، متون رمزی و دانش فراموش‌شده',
        description: 'سال‌ها در کتابخانه‌های ویران والوریا اسرار کفرآمیز را آموخته‌ای؛ ذهن هوشیار و طلسم کهنت درهای تاریکی را می‌گشاید.',
        iconName: 'auto_awesome',
        statBonuses: { arcana: 2, cunning: 1 },
        startingEquipment: {
          mainHand: 'iron_dagger',
          relic: 'shadow_amulet',
        },
        bonusItems: [
          {
            id: 'healing_tincture',
            name: 'معجون گیاهی کوهستان',
            description: 'عصاره تلخ گیاهان کوهستانی که ۳۰ واحد سلامتی (HP) را بازیابی می‌کند.',
            type: 'consumable',
            rarity: 'uncommon',
            quantity: 1,
            healValue: 30,
            isConsumable: true,
          },
        ],
      },
      {
        id: 'silver_diplomat',
        name: 'سفیر نقره‌زبان',
        tagline: 'استاد فریب، مذاکره، زبان‌بازی و ارتباطات پنهان',
        description: 'تیزبین و سخنور؛ در هزارتوی سیاست و دروغ قلعه، کلماتت برنده‌تر از هر شمشیری درهای بسته را باز می‌کنند.',
        iconName: 'record_voice_over',
        statBonuses: { cunning: 2, agility: 1 },
        startingEquipment: {
          mainHand: 'iron_dagger',
        },
        bonusItems: [
          {
            id: 'lockpick_set',
            name: 'ابزار قفل‌گشایی برنجی',
            description: 'دو میله باریک برنجی در غلاف چرمی برای باز کردن قفل‌های زنگ‌زده.',
            type: 'quest_item',
            rarity: 'common',
            quantity: 1,
            statModifiers: { cunning: 1 },
          },
        ],
      },
    ],
    backgrounds: [
      {
        id: 'citadel_outcast',
        name: 'رانده‌شده از قلعه',
        description: 'پیش‌تر خادم دژ بوده‌ای اما پس از کشف رازی ممنوعه به سیاهچال افکنده شدی.',
        trait: 'شناخت گذرگاه‌های مخفی و مجاری خروج آب دژ',
        narrativePromptHook: 'The protagonist was once cast out from the citadel dungeons and intimately knows secret escape shafts.',
        statBonuses: { agility: 1 },
      },
      {
        id: 'guild_infiltrator',
        name: 'نفوذی انجمن مخفی',
        description: 'مزدور کارکشته‌ای که برای دزدیدن نقشه کهن والوریا به قلعه نفوذ کرده است.',
        trait: 'مهارت در باز کردن قفل‌ها و تشخیص تله‌های مکانیکی',
        narrativePromptHook: 'The protagonist is a covert guild agent possessing acute senses for traps and hidden levers.',
        statBonuses: { cunning: 1 },
      },
      {
        id: 'noble_exile',
        name: 'اشراف‌زاده تبعیدی',
        description: 'وارث خاندانی اصیل و سرنگون‌شده که نشان خاندانش را در درز لباس پنهان کرده است.',
        trait: 'آگاهی از نشان‌های سلطنتی و نفوذ کلامی بر نگهبانان اصیل‌زاده',
        narrativePromptHook: 'The protagonist is of noble blood, recognized by highborn guards and versed in court etiquette.',
        statBonuses: { might: 1 },
      },
      {
        id: 'temple_acolyte',
        name: 'نگهبان معبد کهن',
        description: 'شاگرد راهبان معبد خاموش که برای محافظت از آخرین یادگار باستانی به دژ آمده است.',
        trait: 'حس ششم در تشخیص دست‌سازه‌های طلسم‌شده و ارواح سرگردان',
        narrativePromptHook: 'The protagonist has mystical monastic instincts and intuitively senses eldritch relics and cursed wards.',
        statBonuses: { arcana: 1 },
      },
    ],
  },
  worldBible: {
    worldId: 'realm_of_valoria_fa',
    worldName: 'قلمروهای فروپاشیده والوریا',
    summary: 'سرزمینی قرون‌وسطایی که زیر یوغ گارد نقره‌ای اداره می‌شود. هرگونه جادوی باستانی ممنوع و کفرآمیز شمرده می‌شود.',
    themeNotes: 'تاریک، رازآلود، واقع‌گرایانه با فضاسازی سنگ‌های مرطوب، دود مشعل‌ها و دوراهی‌های اخلاقی سنگین.',
    laws: [
      {
        id: 'law_dragons_extinct_fa',
        rule: 'اژدهایان ۳۰۰ سال پیش در پاکسازی بزرگ منقرض شدند.',
        description: 'هیچ اژدهای زنده‌ای در دنیا وجود ندارد. هرگونه ادعایی نشانه جنون یا ارتداد تلقی می‌شود.',
        category: 'creatures',
        isImmutable: true,
      },
      {
        id: 'law_blood_magic_fa',
        rule: 'جادو نیازمند قربانی خون است و در سراسر امپراتوری اکیداً ممنوع می‌باشد.',
        description: 'استفاده از افسون‌ها مجازات اعدام در محل به دست گارد نقره‌ای دارد.',
        category: 'magic',
        isImmutable: true,
      },
    ],
    factions: [
      {
        id: 'silver_guard_fa',
        name: 'گارد نقره‌ای',
        description: 'نیروهای نظامی نخبه تحت فرمان صدراعظم بزرگ.',
        alignment: 'نظم‌گرای سرکوبگر',
        territoryIds: ['loc_citadel_upper_fa', 'loc_guard_hallway_fa'],
        rivalFactionIds: ['shadow_veil_fa'],
        alliedFactionIds: [],
        publicGoals: 'برقراری نظم امپراتوری و سرکوب جادوگران خون.',
      },
      {
        id: 'shadow_veil_fa',
        name: 'نقاب نجوایان',
        description: 'شبکه شورشیان و قاچاقچیان زیرزمینی در دخمه‌های کهن قلعه.',
        alignment: 'بی‌طرف آشوب‌گرا',
        territoryIds: ['loc_subterranean_canals_fa'],
        rivalFactionIds: ['silver_guard_fa'],
        alliedFactionIds: [],
        publicGoals: 'بقا و تجارت قاچاق از مسیرهای مخفی فاضلاب کهن.',
      },
    ],
    locations: [
      {
        id: 'loc_dungeon_cell_fa',
        name: 'سیاه‌چال شماره ۴',
        description: 'سیاه‌چالی سرد که مستقیماً در دل سنگ‌های بازالتی آتشفشان تراشیده شده است.',
        region: 'بخش زیرین قلعه',
        dangerLevel: 2,
        connectedLocationIds: ['loc_guard_hallway_fa'],
        atmosphere: 'سرد، تاریک، بوی نم و خاکستر.',
      },
      {
        id: 'loc_guard_hallway_fa',
        name: 'راهروی سنگین نگهبانی',
        description: 'راهروی مشعل‌دار با کف سنگفرش سنگی که نگهبانان گارد نقره‌ای در آن گشت می‌زنند.',
        region: 'بخش زیرین قلعه',
        dangerLevel: 3,
        connectedLocationIds: ['loc_dungeon_cell_fa', 'loc_subterranean_canals_fa'],
        atmosphere: 'نور لرزان مشعل‌ها، بوی چرم و برق تیغه‌ها.',
      },
      {
        id: 'loc_subterranean_canals_fa',
        name: 'آبراهه‌های نجوایان',
        description: 'فاضلاب کهن و غرقاب شده که با خزه‌های درخشان روشن شده است.',
        region: 'اعماق زیرزمینی',
        dangerLevel: 3,
        connectedLocationIds: ['loc_guard_hallway_fa'],
        atmosphere: 'آب راکد سیاه، بازتاب نجواهای گمشده و بوی رطوبت سنگین.',
      },
      {
        id: 'loc_citadel_upper_fa',
        name: 'تالار بالادست و قدس‌الاقداس دژ',
        description: 'تالار شاهانه با ستون‌های مرمر سیاه و پنجره‌های مشرف به پرتگاه آتشفشان.',
        region: 'بخش فوقانی قلعه',
        dangerLevel: 4,
        connectedLocationIds: ['loc_guard_hallway_fa'],
        atmosphere: 'ستون‌های با عظمت، نور نقره‌ای ماه و سرمای اشرافی.',
      },
    ],
    timeline: [
      {
        id: 'evt_dragon_fall_fa',
        yearOrEra: '۳۰۰ سال پیش (عصر خاکستر)',
        title: 'نبرد بزرگ و انقراض آخرین اژدهایان',
        summary: 'ائتلاف پادشاهان انسان با استفاده از تیغه‌های بازالتی آخرین آشیانه اژدهایان والوریا را در آتش سوزاندند.',
        significance: 'انقراض کامل نسل اژدهایان و تثبیت پادشاهی انسان‌ها در کوهستان سیاه‌سنگ.',
        knownByPublic: true,
        eraCategory: 'ancient',
        linkedLocationIds: ['loc_citadel_upper_fa'],
      },
      {
        id: 'evt_citadel_founding_fa',
        yearOrEra: '۱۸۰ سال پیش',
        title: 'بنا نهادن قلعه سیاه‌سنگ بر دهانه آتشفشان خاموش',
        summary: 'معماران افسانه‌ای دژ نفوذناپذیر سیاه‌سنگ را به عنوان دژی نظامی برای کنترل گذرگاه کوهستانی بنا نهادند.',
        significance: 'مرکزیت سیاسی و نظامی ولایت والوریا.',
        knownByPublic: true,
        eraCategory: 'reign',
        linkedLocationIds: ['loc_citadel_upper_fa', 'loc_guard_hallway_fa'],
      },
      {
        id: 'evt_blood_schism_fa',
        yearOrEra: '۵۰ سال پیش',
        title: 'فرمان ممنوعیت ابدی جادوی سیاه و شکل‌گیری محفل سایه‌ها',
        summary: 'پس از طغیان کیمیاگران دربار، صدراعظم پیشین جادو را غیرقانونی اعلام کرد و بازماندگان به آبراهه‌های مخفی گریختند.',
        significance: 'پیدایش محفل زیرزمینی سایه و کینه دیرینه با گارد نقره‌ای.',
        knownByPublic: false,
        eraCategory: 'war',
        linkedFactionIds: ['silver_guard_fa', 'shadow_veil_fa'],
        linkedLocationIds: ['loc_subterranean_canals_fa'],
        secretDetails: 'کتابخانه ممنوعه کیمیاگران هنوز در پشت دیواره سرداب پنهان است.',
      },
      {
        id: 'evt_current_coup_fa',
        yearOrEra: '۳ ماه پیش (دوره معاصر)',
        title: 'کودتای خاموش صدراعظم و حبس مخالفان در سیاه‌چال',
        summary: 'لرد رولان و نجبای وفادار به تخت مورد اتهام خیانت قرار گرفته و به سیاه‌چال‌های زیرزمینی منتقل شدند.',
        significance: 'بحران مشروعیت و آغاز وقایع داستان قهرمان.',
        knownByPublic: true,
        eraCategory: 'present',
        linkedFactionIds: ['silver_guard_fa'],
        linkedLocationIds: ['loc_dungeon_cell_fa'],
      },
    ],
    npcs: [
      {
        id: 'npc_captain_rolan_fa',
        name: 'کاپیتان رولان',
        title: 'فرمانده دیده‌بان‌های سیاه‌چال',
        factionId: 'silver_guard_fa',
        currentLocationId: 'loc_guard_hallway_fa',
        personalityTraits: ['شرافتمند', 'خسته از جنگ', 'منضبط'],
        speechStyle: 'صدایی خشن و کم‌حرف. تک‌تک حرکات مخاطب را زیر نظر می‌گیرد.',
        goals: ['محافظت از سربازانش', 'کشف حقیقت درباره فساد صدراعظم'],
        secrets: [
          {
            id: 'secret_rolan_doubt_fa',
            description: 'رولان مدارکی یافته که نشان می‌دهد صدراعظم زندانیان بی‌گناه را پاپوش دوخته است.',
            requiredTrustLevel: 20,
            revealed: false,
          },
        ],
        initialTrust: 0,
      },
      {
        id: 'npc_lady_maeve_fa',
        name: 'بانو مهرو',
        title: 'کیمیاگر و سرکرده قاچاقچیان دخمه',
        factionId: 'shadow_veil_fa',
        currentLocationId: 'loc_subterranean_canals_fa',
        personalityTraits: ['حیله‌گر', 'پررمزوراز', 'عمل‌گرا'],
        speechStyle: 'لحنی مخملی، بازیگوشانه و آمیخته با تهدیدهای پنهان.',
        goals: ['قاچاق معجون‌های ممنوعه به بیرون از قلعه', 'سودجویی از هرج‌ومرج حاکم'],
        secrets: [
          {
            id: 'secret_maeve_passage_fa',
            description: 'مهرو کلید عبور از بالابر اختصاصی صدراعظم را در آستین پنهان دارد.',
            requiredTrustLevel: 30,
            revealed: false,
          },
        ],
        initialTrust: 10,
      },
    ],
    artifacts: [
      {
        id: 'art_crown_of_cinders_fa',
        name: 'تاج خاکستر و آتش کهن',
        title: 'تاج پادشاه نخستین والوریا',
        originEra: '۳۰۰ سال پیش (عصر خاکستر)',
        rarity: 'mythic',
        description: 'تاجی ریخته‌شده از استخوان اژدها و طلای مذاب که حرارتی پنهان در فلز آن جاری است.',
        powers: ['کنترل ذهن سربازان کم‌اراده', 'مقاومت مطلق در برابر جادوی آتش'],
        curseOrCost: 'پوشنده آن به مرور دچار جنون شعله و عطش سوزان قدرت می‌شود.',
        attunementRules: 'نیازمند دانش کهن ۱۲ یا هوش ۱۰',
        currentHolderType: 'location',
        currentHolderId: 'loc_citadel_upper_fa',
        secretLore: 'این تاج حاوی آخرین اخگر روح شاه اژدهایان است.',
      },
      {
        id: 'art_shadow_dirk_fa',
        name: 'خنجر سیاه‌تیغ نجوایان',
        title: 'یادگار سرکرده محفل سایه‌ها',
        originEra: '۵۰ سال پیش',
        rarity: 'epic',
        description: 'خنجری از شیشه آتشفشانی تیره که هیچ نوری را بازتاب نمی‌دهد و بدون صدا از هوا می‌گذرد.',
        powers: ['حرکت مخفیانه بی‌صدا', 'افزایش شانس ضربه مهلک (Critical Success)'],
        curseOrCost: 'زخم‌های ناشی از آن تا پیش از طلوع آفتاب بسته نمی‌شوند.',
        currentHolderType: 'npc',
        currentHolderId: 'npc_lady_maeve_fa',
      },
    ],
    bestiary: [
      {
        id: 'creature_basalt_golem_fa',
        name: 'گولم بازالتی اعماق سیاه‌سنگ',
        speciesCategory: 'elemental',
        dangerLevel: 4,
        habitatLocationIds: ['loc_subterranean_canals_fa'],
        behavioralTactics: 'نگهبانی بی‌صدا از گذرگاه‌های زیرزمینی؛ در صورت احساس خطر با ضربات سهمگین زمین‌لرزه به پا می‌کند.',
        weaknesses: ['جادوی یخ و سرمازدگی مفاصل سنگی', 'ضربه کوبشی مستقیم به بلور سینه'],
        resistances: ['مقاومت کامل در برابر جادوی آتش', 'مقاومت در برابر تیغه‌های برنده'],
        harvestableLoot: [
          { itemId: 'basalt_core_gem', name: 'بلور هسته بازالتی', dropRate: '۱۰۰٪' },
          { itemId: 'obsidian_plate_shard', name: 'قطعه زره گدازه‌ای', dropRate: '۵۰٪' },
        ],
        loreDescription: 'سازه‌ای باستانی از جنس سنگ‌های گدازه‌ای سردشده که توسط معماران نخستین قلعه طلسم شده است.',
      },
      {
        id: 'creature_canal_bloodbat_fa',
        name: 'خفاش‌های خون‌نوش کانال',
        speciesCategory: 'beast',
        dangerLevel: 2,
        habitatLocationIds: ['loc_subterranean_canals_fa', 'loc_dungeon_cell_fa'],
        behavioralTactics: 'حمله دسته‌جمعی از سقف‌های تاریک به مسافران تنها در صورت خاموش شدن مشعل.',
        weaknesses: ['نور شدید آتش و مشعل', 'دود گوگردی'],
        resistances: ['فرار سریع از تیرهای پرتابی'],
        harvestableLoot: [
          { itemId: 'bloodbat_wing', name: 'بال خفاش خونین', dropRate: '۸۰٪' },
        ],
        loreDescription: 'گونه‌ای جهش‌یافته از پستانداران غارزی که از عصاره معجون‌های ریخته‌شده در فاضلاب تغذیه می‌کنند.',
      },
    ],
    religions: [
      {
        id: 'deity_lady_of_shadows_fa',
        name: 'بانوی سایه‌ها و گذرگاه‌های خاموش',
        title: 'حافظ عهد کهن و الهه محافظ گمشدگان',
        domain: 'secrets',
        sacredSymbol: 'هلال ماه واژگون از جنس نقره کهنه',
        coreDogma: 'اسرار قدرت حقیقی جهانند؛ هرگز حقیقت برادران و خواهران محفل را به ماموران تاج فاش مکن.',
        taboos: ['روشن کردن مشعل در دخمه‌های مقدس', 'خیانت به پیوند خونین سایه'],
        divineBlessings: ['دید در تاریکی مطلق', 'مهارت مضاعف در فریب و استتار'],
        affiliatedFactionIds: ['shadow_veil_fa'],
        holyLocationIds: ['loc_subterranean_canals_fa'],
      },
      {
        id: 'deity_radiant_arbiter_fa',
        name: 'ایزد داوری و خورشید پولادین',
        title: 'نگهبان نظم ازلی و سرکوبگر جادوی تاریک',
        domain: 'light',
        sacredSymbol: 'شمشیر دو لبه زرین بر زمینه خورشید مشتعل',
        coreDogma: 'هر جادویی فساد است؛ تنها نظم، شمشیر و اقتدار قانون بقای نوع بشر را تضمین می‌کند.',
        taboos: ['پناه دادن به کیمیاگران مرتد', 'عدم اطاعت از فرماندهان گارد'],
        divineBlessings: ['افزایش استقامت و مقاومت در برابر ترس', 'خلوص ذهن در میدان نبرد'],
        affiliatedFactionIds: ['silver_guard_fa'],
        holyLocationIds: ['loc_citadel_upper_fa'],
      },
    ],
    dramaBonds: [
      {
        id: 'bond_rolan_maeve_fa',
        sourceNpcId: 'npc_captain_rolan_fa',
        targetNpcId: 'npc_lady_maeve_fa',
        relationTypeId: 'blood_debt',
        affinity: -25,
        secretTension: 'رولان گمان می‌کرد مهرو سم استفاده شده در قتل نجبای سابق را تهیه کرده؛ اما مهرو می‌داند صدراعظم برای رولان پاپوش دوخته است.',
        isPublic: false,
      },
    ],
  },
  initialSceneId: 'scene_chapter1_fa',
  initialStoryBeats: [
    {
      sceneId: 'scene_chapter1_fa',
      locationId: 'loc_dungeon_cell_fa',
      narrativeText:
        'سرمای سنگ‌های بازالتی به تنت نفوذ می‌کند، پیش از آنکه چشمانت به نور لرزان مشعل از پشت میله‌های آهنی عادت کنند. بوی مس و خاکستر مرطوب فضا را پر کرده است.\n\nاز راهروی روبه‌رو، صدای سنگین گام‌های چکمه‌پوش متوقف می‌شود. کلیدی برنجی در قفل کهنه می‌چرخد. انگشتانت را به آرامی به درز چکمه‌ات می‌رسانی؛ خنجر فولادی هنوز سر جایش است.',
      choices: [
        {
          id: 'choice_fa_1',
          text: 'در گوشه تاریک پشت چارچوب در چوبی پنهان شو.',
          style: 'defensive',
          riskLevel: 'low',
          targetDC: 10,
          requiredStatId: 'agility',
        },
        {
          id: 'choice_fa_2',
          text: 'آرام به سمت نور مشعل برو و بپرس چه کسی نزدیک می‌شود.',
          style: 'diplomatic',
          riskLevel: 'medium',
          targetDC: 12,
          requiredStatId: 'cunning',
        },
        {
          id: 'choice_fa_3',
          text: 'خنجر مخفی‌ات را بکش و در لحظه باز شدن در، برای شبیخون آماده شو.',
          style: 'aggressive',
          riskLevel: 'high',
          targetDC: 14,
          requiredStatId: 'might',
        },
      ],
    },
  ],
};
