import { StoryManifest } from '@/lib/types';

export const obsidianCitadelStory: StoryManifest = {
  id: 'obsidian_citadel',
  title: 'The Obsidian Citadel',
  tagline: 'In the shadow of the black fortress, choices forge your fate.',
  synopsis:
    'Deep beneath the ancient volcanic keep of Black Iron Hold, you awaken to the sound of armored boots echoing against cold stone. The dragons have been dead for three centuries, but something far darker now stirs in the imperial throne room above.',
  genres: ['dark_fantasy', 'mystery_noir'],
  language: 'en',
  coverImageUrl: '/covers/obsidian_citadel.webp',
  author: 'StoryForge Core',
  version: '1.1.0',
  rpgSystem: {
    hasCombat: true,
    diceType: 'd20',
    stats: [
      { id: 'might', name: 'Might', description: 'Raw physical force, endurance and melee power', baseValue: 12 },
      { id: 'agility', name: 'Agility', description: 'Reflexes, stealth, balance and acrobatics', baseValue: 14 },
      { id: 'cunning', name: 'Cunning', description: 'Perception, deception, lockpicking and street wit', baseValue: 10 },
      { id: 'arcana', name: 'Arcana', description: 'Knowledge of blood glyphs and occult relics', baseValue: 8 },
    ],
    resources: [
      { id: 'hp', name: 'Health', current: 100, max: 100, min: 0, color: '#ef4444' },
      { id: 'stamina', name: 'Stamina', current: 50, max: 50, min: 0, color: '#3b82f6' },
      { id: 'gold', name: 'Gold Coins', current: 30, max: 9999, min: 0, color: '#eab308' },
    ],
    skills: [
      { id: 'blade_mastery', name: 'Blade Mastery', description: 'Precision sword strikes', linkedStatId: 'might', tier: 1, bonusModifier: 2 },
      { id: 'shadow_step', name: 'Shadow Step', description: 'Silent movement in darkness', linkedStatId: 'agility', tier: 1, bonusModifier: 2 },
      { id: 'silver_tongue', name: 'Silver Tongue', description: 'Persuasion and fast-talking under pressure', linkedStatId: 'cunning', tier: 1, bonusModifier: 2 },
    ],
    startingInventory: [
      { id: 'iron_dagger', name: 'Iron Dagger', description: 'A notched but razor-sharp boot knife.', type: 'weapon', quantity: 1, statModifiers: { agility: 1 } },
      { id: 'lockpick_set', name: 'Thieves Lockpicks', description: 'Two slender brass picks wrapped in leather.', type: 'quest_item', quantity: 1, statModifiers: { cunning: 1 } },
      { id: 'smoke_pellet', name: 'Alchemical Smoke Pellet', description: 'Creates an instantaneous blinding cloud of grey fog.', type: 'consumable', quantity: 2, isConsumable: true },
    ],
    inventoryCapacity: 10,
    archetypes: [
      {
        id: 'shadowblade',
        name: 'Shadowblade',
        tagline: 'Master of silent infiltration, lockpicking and lethal surprise strikes',
        description: 'Born in the citadel shadows; your footsteps make no sound and your blade strikes before you are ever seen.',
        iconName: 'colorize',
        statBonuses: { agility: 2, cunning: 1 },
        startingEquipment: {
          mainHand: 'iron_dagger',
        },
        bonusItems: [
          { id: 'smoke_pellet', name: 'Alchemical Smoke Pellet', description: 'Blinding cloud of dense fog.', type: 'consumable', quantity: 2, isConsumable: true },
        ],
      },
      {
        id: 'iron_vanguard',
        name: 'Iron Vanguard',
        tagline: 'Stalwart frontline defender with heavy steel and unyielding resolve',
        description: 'Hardened in brutal skirmishes; your broadsword and iron discipline form an impenetrable wall against dungeon terrors.',
        iconName: 'shield',
        statBonuses: { might: 3 },
        startingEquipment: {
          mainHand: 'iron_dagger',
        },
        bonusItems: [
          { id: 'healing_tincture', name: 'Highland Herbal Tincture', description: 'Bitter herbal brew that restores 30 HP instantly.', type: 'consumable', quantity: 1, healValue: 30, isConsumable: true },
        ],
      },
      {
        id: 'arcane_scholar',
        name: 'Arcane Scholar',
        tagline: 'Seeker of forbidden blood glyphs, ancient ciphers and occult truths',
        description: 'Having deciphered forbidden Valorian manuscripts, your keen intellect and arcane insight open doors that steel cannot budge.',
        iconName: 'auto_awesome',
        statBonuses: { arcana: 2, cunning: 1 },
        startingEquipment: {
          mainHand: 'iron_dagger',
        },
        bonusItems: [
          { id: 'healing_tincture', name: 'Highland Herbal Tincture', description: 'Restores 30 HP instantly.', type: 'consumable', quantity: 1, healValue: 30, isConsumable: true },
        ],
      },
      {
        id: 'silver_diplomat',
        name: 'Silver Diplomat',
        tagline: 'Master of deceit, persuasion, court intrigue and high-stakes negotiation',
        description: 'Sharp-tongued and observant; in the citadel labyrinth of lies, your words cut deeper than any blade.',
        iconName: 'record_voice_over',
        statBonuses: { cunning: 2, agility: 1 },
        startingEquipment: {
          mainHand: 'iron_dagger',
        },
        bonusItems: [
          { id: 'lockpick_set', name: 'Thieves Lockpicks', description: 'Slender brass picks wrapped in leather.', type: 'quest_item', quantity: 1, statModifiers: { cunning: 1 } },
        ],
      },
    ],
    backgrounds: [
      {
        id: 'citadel_outcast',
        name: 'Citadel Outcast',
        description: 'Once a servant in the keep until an uncovered secret had you cast into the oubliette.',
        trait: 'Intimate knowledge of secret escape conduits and sewer grates.',
        narrativePromptHook: 'The protagonist was once cast out from the citadel dungeons and intimately knows secret escape shafts.',
        statBonuses: { agility: 1 },
      },
      {
        id: 'guild_infiltrator',
        name: 'Guild Infiltrator',
        description: 'A skilled operative hired to retrieve the lost map of the Lower Vaults.',
        trait: 'Acute sense for detecting mechanical tripwires and hidden levers.',
        narrativePromptHook: 'The protagonist is a covert guild agent possessing acute senses for traps and hidden levers.',
        statBonuses: { cunning: 1 },
      },
      {
        id: 'noble_exile',
        name: 'Exiled Noble',
        description: 'Scion of a disgraced noble house carrying an heirloom crest sewn into your sleeve.',
        trait: 'Natural authority recognized by highborn guards and fluency in court etiquette.',
        narrativePromptHook: 'The protagonist is of noble blood, recognized by highborn guards and versed in court etiquette.',
        statBonuses: { might: 1 },
      },
      {
        id: 'temple_acolyte',
        name: 'Temple Acolyte',
        description: 'A devotee sent to safeguard the final relic before the Silver Guard desecrates it.',
        trait: 'Sixth sense for detecting eldritch runes, cursed wards, and restless spirits.',
        narrativePromptHook: 'The protagonist has mystical monastic instincts and intuitively senses eldritch relics and cursed wards.',
        statBonuses: { arcana: 1 },
      },
    ],
  },
  worldBible: {
    worldId: 'realm_of_valoria',
    worldName: 'The Broken Realms of Valoria',
    summary: 'A dark medieval continent shattered by ancient wars. Magic is heavily policed and considered heretical by the Silver Guard.',
    themeNotes: 'Gritty, atmospheric, high tension, low fantasy realism. Focus on tactile physical descriptions, cold stone, torchlight, and moral ambiguity.',
    laws: [
      {
        id: 'law_dragons_extinct',
        rule: 'Dragons became extinct 300 years ago during the Great Purge.',
        description: 'No living dragons exist anywhere in the world. Anyone claiming otherwise is considered mad or a heretic.',
        category: 'creatures',
        isImmutable: true,
      },
      {
        id: 'law_blood_magic',
        rule: 'Magic requires blood sacrifice and is strictly outlawed across the empire.',
        description: 'Casting spells drains the lifeforce of living beings. The Silver Guard executes rogue practitioners on sight.',
        category: 'magic',
        isImmutable: true,
      },
      {
        id: 'law_iron_gate',
        rule: 'The Citadel Lower Vaults can only be unlocked from the inner guard station.',
        description: 'The massive portcullis cannot be breached with physical force alone.',
        category: 'physics',
        isImmutable: true,
      },
    ],
    factions: [
      {
        id: 'silver_guard',
        name: 'The Silver Guard',
        description: 'The martial elite enforcers of the Grand Chancellor.',
        alignment: 'Lawful Authoritarian',
        territoryIds: ['loc_citadel_upper', 'loc_citadel_barracks', 'loc_guard_hallway'],
        rivalFactionIds: ['shadow_veil'],
        alliedFactionIds: [],
        publicGoals: 'Maintain imperial order and stamp out blood magic heresy.',
        secretAgendas: 'The Chancellor seeks to awaken ancient forbidden artifacts.',
      },
      {
        id: 'shadow_veil',
        name: 'The Whispering Veil',
        description: 'Underground smuggler and rebel network operating in the forgotten catacombs.',
        alignment: 'Chaotic Neutral',
        territoryIds: ['loc_citadel_lower', 'loc_subterranean_canals', 'loc_alchemist_den'],
        rivalFactionIds: ['silver_guard'],
        alliedFactionIds: [],
        publicGoals: 'Survival and illicit trade through forgotten subterranean routes.',
      },
    ],
    locations: [
      {
        id: 'loc_dungeon_cell',
        name: 'Subterranean Cell Block IV',
        description: 'Damp vaulted dungeon carved directly into volcanic basalt. Water drips from rusty iron ceiling grates.',
        region: 'Lower Citadel',
        dangerLevel: 2,
        connectedLocationIds: ['loc_guard_hallway', 'loc_drainage_pipe'],
        atmosphere: 'Cold, claustrophobic, iron and mildew.',
      },
      {
        id: 'loc_guard_hallway',
        name: 'Iron Gate Sentry Post',
        description: 'Torchlit stone corridor guarded by Silver Guard sentries.',
        region: 'Lower Citadel',
        dangerLevel: 3,
        connectedLocationIds: ['loc_dungeon_cell', 'loc_armory', 'loc_subterranean_canals'],
        atmosphere: 'Flickering torchlight, heavy leather and polished steel.',
      },
      {
        id: 'loc_subterranean_canals',
        name: 'The Whispering Canals',
        description: 'Flooded ancient sewers illuminated by eerie bioluminescent moss.',
        region: 'Under-Citadel',
        dangerLevel: 3,
        connectedLocationIds: ['loc_guard_hallway', 'loc_alchemist_den', 'loc_grand_sanctum'],
        atmosphere: 'Stagnant dark water, echoing whispers, damp moss.',
      },
      {
        id: 'loc_alchemist_den',
        name: 'Maeve\'s Alchemical Sanctum',
        description: 'Hidden underground laboratory packed with bubbling alembics, rare herbs, and contraband manuscripts.',
        region: 'Under-Citadel',
        dangerLevel: 1,
        connectedLocationIds: ['loc_subterranean_canals'],
        atmosphere: 'Pungent sulfur, dried lavender, and warm hearth glow.',
      },
      {
        id: 'loc_grand_sanctum',
        name: 'The Chancellor\'s High Keep',
        description: 'Opulent gothic throne room crowned with obsidian pillars and crimson velvet tapestries.',
        region: 'Upper Citadel',
        dangerLevel: 5,
        connectedLocationIds: ['loc_subterranean_canals'],
        atmosphere: 'Heavy incense, shimmering silver banners, suffocating royal authority.',
      },
    ],
    timeline: [
      {
        id: 'time_purge',
        yearOrEra: '300 Years Ago (Age of Ash)',
        title: 'The Great Dragon Purge',
        summary: 'The united human kings used basalt-forged greatswords to exterminate the dragon sky-lords of Mount Obsidian.',
        significance: 'Total extinction of draconic apex predators and establishment of mortal hegemony.',
        knownByPublic: true,
        eraCategory: 'ancient',
        linkedLocationIds: ['loc_grand_sanctum'],
      },
      {
        id: 'time_founding',
        yearOrEra: '180 Years Ago',
        title: 'Founding of the Obsidian Citadel',
        summary: 'Master masons erected the black stone citadel atop the dormant volcano to secure the mountain pass.',
        significance: 'Establishment of the military heart of the realm.',
        knownByPublic: true,
        eraCategory: 'reign',
        linkedLocationIds: ['loc_grand_sanctum', 'loc_guard_hallway'],
      },
      {
        id: 'time_schism',
        yearOrEra: '50 Years Ago',
        title: 'The Blood Edict & Outlawing of Alchemy',
        summary: 'Following an arcane uprising in the court, blood magic was decreed high treason and dissenters fled underground.',
        significance: 'Birth of the Shadow Veil syndicate and bitter ideological rivalry with the Silver Guard.',
        knownByPublic: false,
        eraCategory: 'war',
        linkedFactionIds: ['silver_guard', 'shadow_veil'],
        linkedLocationIds: ['loc_subterranean_canals', 'loc_alchemist_den'],
        secretDetails: 'A forbidden arcane archive remains sealed behind the subterranean vault wall.',
      },
      {
        id: 'time_coup',
        yearOrEra: '3 Months Ago (Present Day)',
        title: 'The Silent Coup & Dungeon Imprisonments',
        summary: 'The Chancellor seized executive command and began purging royalist nobles into the lower vault cells.',
        significance: 'Legitimacy crisis and the catalyst for the player\'s awakening.',
        knownByPublic: true,
        eraCategory: 'present',
        linkedFactionIds: ['silver_guard'],
        linkedLocationIds: ['loc_dungeon_cell'],
      },
    ],
    npcs: [
      {
        id: 'npc_captain_rolan',
        name: 'Captain Rolan',
        title: 'Sentry Commander of the Lower Vaults',
        factionId: 'silver_guard',
        currentLocationId: 'loc_guard_hallway',
        personalityTraits: ['Honorable', 'Weary', 'Disciplined'],
        speechStyle: 'Low, rasping voice. Speaks sparingly and evaluates every move.',
        goals: ['Protect his men', 'Uncover if the Chancellor is truly corrupt'],
        secrets: [
          {
            id: 'secret_rolan_doubt',
            description: 'Rolan found documents proving the Chancellor framed innocent prisoners.',
            requiredTrustLevel: 20,
            revealed: false,
          },
        ],
        initialTrust: 0,
      },
      {
        id: 'npc_lady_maeve',
        name: 'Lady Maeve',
        title: 'Alchemist & Smuggler Queen',
        factionId: 'shadow_veil',
        currentLocationId: 'loc_alchemist_den',
        personalityTraits: ['Cunning', 'Flamboyant', 'Pragmatic'],
        speechStyle: 'Playful, velvety tone laced with subtle veiled threats.',
        goals: ['Smuggle prohibited arcane reagents past the blockade', 'Profit from chaos'],
        secrets: [
          {
            id: 'secret_maeve_passage',
            description: 'Maeve possesses a secret key to the Chancellor\'s private vault lift.',
            requiredTrustLevel: 30,
            revealed: false,
          },
        ],
        initialTrust: 10,
      },
    ],
    artifacts: [
      {
        id: 'art_crown_of_cinders',
        name: 'The Crown of Cinders',
        title: 'Heirloom of the First Sovereign',
        originEra: '300 Years Ago (Age of Ash)',
        rarity: 'mythic',
        description: 'A coronet cast in blackened dragon bone and molten gold that radiates unearthly volcanic warmth.',
        powers: ['Subjugate weak-willed sentries', 'Absolute immunity to flame-based attacks'],
        curseOrCost: 'Slowly induces paranoid pyromania and unquenchable thirst for domination.',
        attunementRules: 'Requires Arcana 12 or Cunning 10',
        currentHolderType: 'location',
        currentHolderId: 'loc_grand_sanctum',
        secretLore: 'Houses the dormant celestial spark of the slain Sky-Lord Ignis.',
      },
      {
        id: 'art_shadow_dirk',
        name: 'The Whispering Stiletto',
        title: 'Relic of the Shadow Veil Matron',
        originEra: '50 Years Ago',
        rarity: 'epic',
        description: 'Forged from frosted obsidian that absorbs all ambient light and parts flesh without friction.',
        powers: ['Grants absolute silent footwork', 'Boosts Critical Hit chance on unaware targets'],
        curseOrCost: 'Wounds inflicted cannot be healed by natural means before sunrise.',
        currentHolderType: 'npc',
        currentHolderId: 'npc_lady_maeve',
      },
    ],
    bestiary: [
      {
        id: 'creature_basalt_golem',
        name: 'The Basalt Guardian Golem',
        speciesCategory: 'elemental',
        dangerLevel: 4,
        habitatLocationIds: ['loc_subterranean_canals'],
        behavioralTactics: 'Stationary sentinel in waterlogged passages; unleashes seismic ground slams if breached.',
        weaknesses: ['Frost damage freezing stone joints', 'Blunt concussive blows to chest core crystal'],
        resistances: ['Complete immunity to fire and lava', 'Heavy slash and piercing resistance'],
        harvestableLoot: [
          { itemId: 'basalt_core_gem', name: 'Basalt Core Crystal', dropRate: '100%' },
          { itemId: 'obsidian_plate_shard', name: 'Lava-Forged Plating', dropRate: '50%' },
        ],
        loreDescription: 'Ancient autonomous war golem sculpted from dormant volcanic basalt and bound by royal sigils.',
      },
      {
        id: 'creature_canal_bloodbat',
        name: 'Whispering Canal Bloodbats',
        speciesCategory: 'beast',
        dangerLevel: 2,
        habitatLocationIds: ['loc_subterranean_canals', 'loc_dungeon_cell'],
        behavioralTactics: 'Swarm ambush from ceiling recesses when illumination dims or torch fails.',
        weaknesses: ['High intensity torchlight and flash bombs', 'Sulfur smoke dispersal'],
        resistances: ['Evasion against single-target projectile attacks'],
        harvestableLoot: [
          { itemId: 'bloodbat_wing', name: 'Alchemical Bat Wing', dropRate: '80%' },
        ],
        loreDescription: 'Mutated cavern bats sustained by spilled alchemical reagents draining into the sewer pools.',
      },
    ],
    religions: [
      {
        id: 'deity_lady_of_shadows',
        name: 'The Lady of Whispers & Veils',
        title: 'Guardian of Forgotten Covenants & The Outcast',
        domain: 'secrets',
        sacredSymbol: 'Inverted crescent moon forged from tarnished silver',
        coreDogma: 'Secrets are the primordial currency of true power; never surrender a sibling of the Veil to imperial inquisitors.',
        taboos: ['Igniting open torches in sanctified crypts', 'Betraying a blood oath'],
        divineBlessings: ['Uncanny night vision', 'Bonus to stealth and deception maneuvers'],
        affiliatedFactionIds: ['shadow_veil'],
        holyLocationIds: ['loc_subterranean_canals', 'loc_alchemist_den'],
      },
      {
        id: 'deity_radiant_arbiter',
        name: 'The Radiant Sovereign of Iron',
        title: 'Keeper of Martial Order & Purger of Occult Arts',
        domain: 'light',
        sacredSymbol: 'Golden greatsword superimposed over a blazing sun',
        coreDogma: 'All sorcery is corruption; only iron discipline, the sword, and royal decree sustain mortal civilization.',
        taboos: ['Harboring apostate alchemists', 'Refusing a commander\'s direct combat order'],
        divineBlessings: ['Enhanced composure against panic and fear', 'Unshakable focus in melee clashes'],
        affiliatedFactionIds: ['silver_guard'],
        holyLocationIds: ['loc_grand_sanctum'],
      },
    ],
    dramaBonds: [
      {
        id: 'bond_rolan_maeve',
        sourceNpcId: 'npc_captain_rolan',
        targetNpcId: 'npc_lady_maeve',
        relationTypeId: 'blood_debt',
        affinity: -25,
        secretTension: 'Rolan suspected Maeve supplied the lethal venom used on the royal magistrate; Maeve secretly holds proof that the Chancellor framed Rolan\'s garrison.',
        isPublic: false,
      },
    ],
  },
  initialSceneId: 'scene_chapter1_awakening',
  initialStoryBeats: [
    {
      sceneId: 'scene_chapter1_awakening',
      locationId: 'loc_dungeon_cell',
      narrativeText:
        'The cold stone bites into your back before your eyes even adjust to the dim glow of torchlight through the iron bars. Heavy armored boots halt outside and a key turns in the bronze lock.',
      choices: [
        {
          id: 'choice_1',
          text: 'Conceal yourself in the shadowy corner behind the door.',
          style: 'defensive',
          riskLevel: 'low',
          targetDC: 10,
          requiredStatId: 'agility',
          targetSceneId: 'scene_stealth_hallway',
        },
        {
          id: 'choice_2',
          text: 'Step forward into the light and parley with Captain Rolan.',
          style: 'diplomatic',
          riskLevel: 'medium',
          targetDC: 12,
          requiredStatId: 'cunning',
          targetSceneId: 'scene_parley_rolan',
        },
        {
          id: 'choice_3',
          text: 'Draw your hidden knife and ambush the sentry as the door opens.',
          style: 'aggressive',
          riskLevel: 'high',
          targetDC: 14,
          requiredStatId: 'might',
          targetSceneId: 'scene_sentry_skirmish',
        },
      ],
    },
    {
      sceneId: 'scene_stealth_hallway',
      locationId: 'loc_guard_hallway',
      narrativeText:
        'You slip past the distracted guard into the damp corridor. A vaulted staircase descends into the subterranean canals.',
      choices: [
        {
          id: 'choice_stealth_1',
          text: 'Descend into the canal waterways.',
          style: 'agile',
          riskLevel: 'low',
          targetDC: 10,
          requiredStatId: 'agility',
          targetSceneId: 'scene_canal_escape',
        },
      ],
    },
    {
      sceneId: 'scene_parley_rolan',
      locationId: 'loc_guard_hallway',
      narrativeText:
        'Captain Rolan lowers his blade as you reveal the noble seal of House Valoria. He offers safe passage toward the underground canals.',
      choices: [
        {
          id: 'choice_parley_1',
          text: 'Accept Rolan\'s escort toward the canal gates.',
          style: 'diplomatic',
          riskLevel: 'medium',
          targetDC: 12,
          requiredStatId: 'cunning',
          targetSceneId: 'scene_canal_escape',
        },
      ],
    },
    {
      sceneId: 'scene_sentry_skirmish',
      locationId: 'loc_dungeon_cell',
      narrativeText:
        'Your strike knocks the armored guard to the floor. Alarms echo down the hall—you grab the keys and sprint for the canal passage!',
      choices: [
        {
          id: 'choice_skirmish_1',
          text: 'Sprint down the stairs to the canal boats.',
          style: 'aggressive',
          riskLevel: 'high',
          targetDC: 12,
          requiredStatId: 'might',
          targetSceneId: 'scene_canal_escape',
        },
      ],
    },
    {
      sceneId: 'scene_canal_escape',
      locationId: 'loc_subterranean_canals',
      narrativeText:
        'Lady Maeve maneuvers her smuggler barge alongside the stone jetty, offering escape into the misty river outside the citadel.',
      choices: [
        {
          id: 'choice_escape_1',
          text: 'Board the barge and escape into the mist.',
          style: 'diplomatic',
          riskLevel: 'low',
          targetDC: 10,
          requiredStatId: 'cunning',
        },
      ],
    },
  ],
};

