import { StoryManifest } from '@/lib/types';

export const obsidianCitadelStory: StoryManifest = {
  id: 'obsidian_citadel',
  title: 'The Obsidian Citadel',
  tagline: 'In the shadow of the black fortress, choices forge your fate.',
  synopsis:
    'Deep beneath the ancient volcanic keep of Black Iron Hold, you awaken to the sound of armored boots echoing against cold stone. The dragons have been dead for three centuries, but something far darker now stirs in the imperial throne room above.',
  genres: ['dark_fantasy', 'mystery_noir'],
  language: 'en',
  coverImageUrl: '/covers/obsidian_citadel.webp',
  author: 'StoryForge Core',
  version: '1.1.0',
  rpgSystem: {
    hasCombat: true,
    diceType: 'd20',
    stats: [
      { id: 'might', name: 'Might', description: 'Raw physical force, endurance and melee power', baseValue: 12 },
      { id: 'agility', name: 'Agility', description: 'Reflexes, stealth, balance and acrobatics', baseValue: 14 },
      { id: 'cunning', name: 'Cunning', description: 'Perception, deception, lockpicking and street wit', baseValue: 10 },
      { id: 'arcana', name: 'Arcana', description: 'Knowledge of blood glyphs and occult relics', baseValue: 8 },
    ],
    resources: [
      { id: 'hp', name: 'Health', current: 100, max: 100, min: 0, color: '#ef4444' },
      { id: 'stamina', name: 'Stamina', current: 50, max: 50, min: 0, color: '#3b82f6' },
      { id: 'gold', name: 'Gold Coins', current: 30, max: 9999, min: 0, color: '#eab308' },
    ],
    skills: [
      { id: 'blade_mastery', name: 'Blade Mastery', description: 'Precision sword strikes', linkedStatId: 'might', tier: 1, bonusModifier: 2 },
      { id: 'shadow_step', name: 'Shadow Step', description: 'Silent movement in darkness', linkedStatId: 'agility', tier: 1, bonusModifier: 2 },
      { id: 'silver_tongue', name: 'Silver Tongue', description: 'Persuasion and fast-talking under pressure', linkedStatId: 'cunning', tier: 1, bonusModifier: 2 },
    ],
    startingInventory: [
      { id: 'iron_dagger', name: 'Iron Dagger', description: 'A notched but razor-sharp boot knife.', type: 'weapon', quantity: 1, statModifiers: { agility: 1 } },
      { id: 'lockpick_set', name: 'Thieves Lockpicks', description: 'Two slender brass picks wrapped in leather.', type: 'quest_item', quantity: 1, statModifiers: { cunning: 1 } },
      { id: 'smoke_pellet', name: 'Alchemical Smoke Pellet', description: 'Creates an instantaneous blinding cloud of grey fog.', type: 'consumable', quantity: 2, isConsumable: true },
    ],
    inventoryCapacity: 10,
  },
  worldBible: {
    worldId: 'realm_of_valoria',
    worldName: 'The Broken Realms of Valoria',
    summary: 'A dark medieval continent shattered by ancient wars. Magic is heavily policed and considered heretical by the Silver Guard.',
    themeNotes: 'Gritty, atmospheric, high tension, low fantasy realism. Focus on tactile physical descriptions, cold stone, torchlight, and moral ambiguity.',
    laws: [
      {
        id: 'law_dragons_extinct',
        rule: 'Dragons became extinct 300 years ago during the Great Purge.',
        description: 'No living dragons exist anywhere in the world. Anyone claiming otherwise is considered mad or a heretic.',
        category: 'creatures',
        isImmutable: true,
      },
      {
        id: 'law_blood_magic',
        rule: 'Magic requires blood sacrifice and is strictly outlawed across the empire.',
        description: 'Casting spells drains the lifeforce of living beings. The Silver Guard executes rogue practitioners on sight.',
        category: 'magic',
        isImmutable: true,
      },
      {
        id: 'law_iron_gate',
        rule: 'The Citadel Lower Vaults can only be unlocked from the inner guard station.',
        description: 'The massive portcullis cannot be breached with physical force alone.',
        category: 'physics',
        isImmutable: true,
      },
    ],
    factions: [
      {
        id: 'silver_guard',
        name: 'The Silver Guard',
        description: 'The martial elite enforcers of the Grand Chancellor.',
        alignment: 'Lawful Authoritarian',
        territoryIds: ['loc_citadel_upper', 'loc_citadel_barracks', 'loc_guard_hallway'],
        rivalFactionIds: ['shadow_veil'],
        alliedFactionIds: [],
        publicGoals: 'Maintain imperial order and stamp out blood magic heresy.',
        secretAgendas: 'The Chancellor seeks to awaken ancient forbidden artifacts.',
      },
      {
        id: 'shadow_veil',
        name: 'The Whispering Veil',
        description: 'Underground smuggler and rebel network operating in the forgotten catacombs.',
        alignment: 'Chaotic Neutral',
        territoryIds: ['loc_citadel_lower', 'loc_subterranean_canals', 'loc_alchemist_den'],
        rivalFactionIds: ['silver_guard'],
        alliedFactionIds: [],
        publicGoals: 'Survival and illicit trade through forgotten subterranean routes.',
      },
    ],
    locations: [
      {
        id: 'loc_dungeon_cell',
        name: 'Subterranean Cell Block IV',
        description: 'Damp vaulted dungeon carved directly into volcanic basalt. Water drips from rusty iron ceiling grates.',
        region: 'Lower Citadel',
        dangerLevel: 2,
        connectedLocationIds: ['loc_guard_hallway', 'loc_drainage_pipe'],
        atmosphere: 'Cold, claustrophobic, iron and mildew.',
      },
      {
        id: 'loc_guard_hallway',
        name: 'Iron Gate Sentry Post',
        description: 'Torchlit stone corridor guarded by Silver Guard sentries.',
        region: 'Lower Citadel',
        dangerLevel: 3,
        connectedLocationIds: ['loc_dungeon_cell', 'loc_armory', 'loc_subterranean_canals'],
        atmosphere: 'Flickering torchlight, heavy leather and polished steel.',
      },
      {
        id: 'loc_subterranean_canals',
        name: 'The Whispering Canals',
        description: 'Flooded ancient sewers illuminated by eerie bioluminescent moss.',
        region: 'Under-Citadel',
        dangerLevel: 3,
        connectedLocationIds: ['loc_guard_hallway', 'loc_alchemist_den', 'loc_grand_sanctum'],
        atmosphere: 'Stagnant dark water, echoing whispers, damp moss.',
      },
      {
        id: 'loc_alchemist_den',
        name: 'Maeve\'s Alchemical Sanctum',
        description: 'Hidden underground laboratory packed with bubbling alembics, rare herbs, and contraband manuscripts.',
        region: 'Under-Citadel',
        dangerLevel: 1,
        connectedLocationIds: ['loc_subterranean_canals'],
        atmosphere: 'Pungent sulfur, dried lavender, and warm hearth glow.',
      },
      {
        id: 'loc_grand_sanctum',
        name: 'The Chancellor\'s High Keep',
        description: 'Opulent gothic throne room crowned with obsidian pillars and crimson velvet tapestries.',
        region: 'Upper Citadel',
        dangerLevel: 5,
        connectedLocationIds: ['loc_subterranean_canals'],
        atmosphere: 'Heavy incense, shimmering silver banners, suffocating royal authority.',
      },
    ],
    timeline: [
      {
        id: 'time_purge',
        yearOrEra: 'Year 720 of the Sun',
        title: 'The Great Dragon Purge',
        summary: 'The last dragon sky-lord was slain at Mount Obsidian, ending the Age of Scales.',
        significance: 'Extinction of dragonkind.',
        knownByPublic: true,
      },
    ],
    npcs: [
      {
        id: 'npc_captain_rolan',
        name: 'Captain Rolan',
        title: 'Sentry Commander of the Lower Vaults',
        factionId: 'silver_guard',
        currentLocationId: 'loc_guard_hallway',
        personalityTraits: ['Honorable', 'Weary', 'Disciplined'],
        speechStyle: 'Low, rasping voice. Speaks sparingly and evaluates every move.',
        goals: ['Protect his men', 'Uncover if the Chancellor is truly corrupt'],
        secrets: [
          {
            id: 'secret_rolan_doubt',
            description: 'Rolan found documents proving the Chancellor framed innocent prisoners.',
            requiredTrustLevel: 20,
            revealed: false,
          },
        ],
        initialTrust: 0,
      },
      {
        id: 'npc_lady_maeve',
        name: 'Lady Maeve',
        title: 'Alchemist & Smuggler Queen',
        factionId: 'shadow_veil',
        currentLocationId: 'loc_alchemist_den',
        personalityTraits: ['Cunning', 'Flamboyant', 'Pragmatic'],
        speechStyle: 'Playful, velvety tone laced with subtle veiled threats.',
        goals: ['Smuggle prohibited arcane reagents past the blockade', 'Profit from chaos'],
        secrets: [
          {
            id: 'secret_maeve_passage',
            description: 'Maeve possesses a secret key to the Chancellor\'s private vault lift.',
            requiredTrustLevel: 30,
            revealed: false,
          },
        ],
        initialTrust: 10,
      },
    ],
  },
  initialSceneId: 'scene_chapter1_awakening',
  initialStoryBeats: [
    {
      sceneId: 'scene_chapter1_awakening',
      locationId: 'loc_dungeon_cell',
      narrativeText:
        'The cold stone bites into your back before your eyes even adjust to the dim glow of torchlight through the iron bars. The air tastes of copper and damp ash.\n\nFrom the corridor beyond your cell, heavy armored boots come to a halt. A key scrapes against the bronze lock. You slip your fingers down to the seam of your boot—the concealed iron blade is still there.',
      choices: [
        {
          id: 'choice_1',
          text: 'Conceal yourself in the shadowy corner behind the heavy wooden door frame.',
          style: 'defensive',
          riskLevel: 'low',
          targetDC: 10,
          requiredStatId: 'agility',
        },
        {
          id: 'choice_2',
          text: 'Step forward calmly into the torchlight and demand to know who approaches.',
          style: 'diplomatic',
          riskLevel: 'medium',
          targetDC: 12,
          requiredStatId: 'cunning',
        },
        {
          id: 'choice_3',
          text: 'Draw your hidden boot knife and prepare an ambush strike the moment the door swings open.',
          style: 'aggressive',
          riskLevel: 'high',
          targetDC: 14,
          requiredStatId: 'might',
        },
      ],
    },
  ],
};
